title: "Text Classification"
description: | 
  This project uses spaCy to train a text classifier on github issues
# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  name: "textcat_github_issues"
  version: "0.0.1"
  # Choose your GPU here
  gpu_id: 0
  # Change this to "bert" to use the transformer-based model
  config: "bert"

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["assets", "training", "configs", "metrics", "packages", "scripts", "corpus"]

# Assets that should be downloaded or available in the directory.
assets:
  - dest: "assets/train.jsonl"
    url: "https://raw.githubusercontent.com/PacktPublishing/Mastering-spaCy-Second-Edition./main/chapter_09/data/train.jsonl"
    description: "The training data"
  - dest: "assets/dev.jsonl"
    url: "https://raw.githubusercontent.com/PacktPublishing/Mastering-spaCy-Second-Edition./main/chapter_09/data/dev.jsonl"
    description: "The development data"
  - dest: "assets/eval.jsonl"
    url: "https://raw.githubusercontent.com/PacktPublishing/Mastering-spaCy-Second-Edition./main/chapter_09/data/eval.jsonl"
    description: "The evaluation data"

# Workflows are sequences of commands (see below) executed in order. You can
# run them via "spacy project run [workflow]". If a commands's inputs/outputs
# haven't changed, it won't be re-run.
workflows:
  all:
    - preprocess
    - train

# Project commands, specified in a style similar to CI config files (e.g. Azure
# pipelines). The name is the command name that lets you trigger the command
# via "spacy project run [command] [path]". The help message is optional and
# shown when executing "spacy project run [optional command] [path] --help".
commands:
  - name: init-vectors
    help: Download vectors and convert to model
    script:
      - "python -m spacy init vectors en assets/vectors.zip assets/en_fasttext_vectors"
    deps:
      - "assets/vectors.zip"
    outputs_no_cache:
      - "assets/en_vectors_web_lg"

  - name: preprocess
    help: "Convert the corpus to spaCy's format"
    script:
      - "python scripts/convert.py"
    deps:
      - "assets/train.jsonl"
      - "assets/dev.jsonl"
      - "assets/eval.jsonl"
    outputs_no_cache:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "corpus/eval.spacy"

  - name: train
    help: "Train a spaCy pipeline using the specified corpus and config"
    script:
      - "python -m spacy train ./configs/${vars.config}.cfg -o training/${vars.config} --gpu-id ${vars.gpu_id}"
    deps:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "configs/${vars.config}.cfg"
    outputs:
      - "training/${vars.config}/model-best"

  - name: evaluate
    help: "Evaluate the model and export metrics"
    script:
      - "python -m spacy evaluate training/${vars.config}/model-best corpus/eval.spacy --output training/${vars.config}/metrics.json"
    deps:
      - "corpus/eval.spacy"
      - "training/${vars.config}/model-best"
    outputs:
      - "training/${vars.config}/metrics.json"

  - name: package
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package ./training/${vars.config}/model-best packages/ --name ${vars.name} --force --version ${vars.version} --build wheel --meta-path meta.json"
    deps:
      - "training/${vars.config}/model-best"
    outputs_no_cache:
      - "packages/${vars.name}-${vars.version}/dist/${vars.name}-${vars.version}.tar.gz"

  - name: visualize
    help: Visualize the model's output interactively using Streamlit
    script:
      - "streamlit run scripts/visualize_model.py training/${vars.config}/model-best \"I’m sorry to hear that friend :(\""
    deps:
      - "scripts/visualize_model.py"
      - "training/${vars.config}/model-best"
